### ISSUE TITLE
Custom support libs

### ISSUE THREAD

**Issue by MrAta** [aws-samples/aws-lambda-extensions#1]
Taking the [python extension example](https://github.com/aws-samples/aws-lambda-extensions/tree/main/python-example-extension) as an example, I wanted to have an extension that uses [ebpf bcc](https://github.com/iovisor/bcc) tools python frontend. But, just adding `bcc` to the `requirements.txt` and ship it with the extension code is not enough. It needs the `BCC` tools to be installed as well. In the case of lambda, assuming it's running on Amazon Linux 2, even though the BPF kernel config flags are set, one still would need to run `sudo amazon-linux-extras install BCC` to install it, and then the extension python code will be able to run bcc frontend such as `BPF()` function. 

I tried to run the install command as part of extension initialization, but seems it doesn't recognize the command.

I was wondering if there's a way to do that or not?

**Comment by julianwood** [comment]
Lambda does not allow kernel level operations at this stage for managed runtimes. Perhaps there would be a way to get this working using a Lambda function packaged as a container image where you build your Linux environment and install all necessary dependencies.

**Comment by chadbrewbaker** [comment]
Use the stock awslinux:2 containter to mirror the awslinux2 generic runtime?

How do you elevate the container permissions for ebpf privildges? Where is the kernel source for what Lambda container instances are running?

This is how I get kernel source on Docker of Mac:
```bash
FROM docker/for-desktop-kernel:5.15.49-13422a825f833d125942948cf8a8688cef721ead AS ksource
FROM ubuntu:22.04
WORKDIR /
COPY --from=ksource /kernel-dev.tar /
RUN tar xf kernel-dev.tar
```
