### ISSUE TITLE
A couple of minor java-example-extension issues

### ISSUE THREAD

**Issue by DmitryGulin** [aws-samples/aws-lambda-extensions#18]
I was trying to follow README steps and deploy java extensions example and noticed a couple of small issues with it:

1. target folder, as well as .jar and .zip files and VSCode .settings folder - all are missing in .gitignore;
2. zip.sh and run.sh scripts have incorrect command ordering, which resulted in the following error:
> chmod: extensions/java-example-extension: No such file or directory

**Comment by santiagocardenas** [comment]
Issues fixed.
