### ISSUE TITLE
Example request: Intercept lambda invoke with nodejs

### ISSUE THREAD

**Issue by liveFreeOrCode** [aws-samples/aws-lambda-extensions#49]
Is it possible for internal extensions to be able to intercept a lambda invocation event or response? I want to build essentially a wrapper function that is meant to validate certain properties of both incoming event payloads and responses.

I saw the example here for a javaagent to intercept the lambda invocations, and wasn't sure if this was possible with node in any way? https://docs.aws.amazon.com/lambda/latest/dg/runtimes-modify.html

**Comment by julianwood** [comment]
Currently I don't believe this is possible with Node.
