### ISSUE TITLE
ARM64

### ISSUE THREAD

**Issue by aterreno** [aws-samples/aws-lambda-extensions#57]
Am I right in saying that the lambda extension layer won't work on ARM64/graviton processors? 

Thanks

**Comment by julianwood** [comment]
A Lambda extension layer is just files. If the files within the layer are compatible with ARM64/Graviton2 then the extension will work. Interpreted languages like Node/Python work without modification. If you're building extensions using binaries, these will need to be rebuild for arm64.

**Comment by aterreno** [comment]
thanks @julianwood  - I tried the lambda extension layer some time ago (in combination with datadog layer) and I had issues

we got back:

```fork/exec /opt/extensions/cloudwatch_lambda_agent: exec format error```

Although this might not be the right repository, I can't find where else I should raise this with AWS

**Comment by julianwood** [comment]
Are you using CloudWatch Lambda Insights? The extension for this was only updated yesterday to work with Graviton2. Currently we're waiting for CloudFormation and CDK/SAM support to be rolled out. 
You should be able to deselect in the console and select again which will add the correct Graviton2 supported Lambda layer.

**Comment by aterreno** [comment]
Oh amazing news, I had to remove it to be able to move all our lambdas to Graviton

**Comment by aterreno** [comment]
Just in case anyone else stumbles here and they are using terraform or pulumi to manage their infra, the arn for the layer is:

arn:aws:lambda:us-east-1:580247275435:layer:LambdaInsightsExtension-Arm64:1 

or whatever region your lambda is deployed into :)

**Comment by julianwood** [comment]
Thanks, glad you're sorted!
