### ISSUE TITLE
Lambda Extension to send logs directly to Kinesis Data Streams

### ISSUE THREAD

**Issue by ravinaik1312** [aws-samples/aws-lambda-extensions#58]
Lambda extension to send logs directly to Kinesis Data Streams in order to facilitate centralized logging. The logs should only be streamed to the Kinesis Data Streams service rather than sending it to CloudWatch and creating a subscription around this.

**Comment by julianwood** [comment]
Merged: https://github.com/aws-samples/aws-lambda-extensions/pull/59
