### ISSUE TITLE
Add extension example for java corretto 8

### ISSUE THREAD

**Issue by RobertoC27** [aws-samples/aws-lambda-extensions#6]
Hello we are currently working with the corretto 8 runtime and would benefit from using an extension.

Right now our function starts a external process with each invocation that is stopped at the end, given that this process just needs to be closed when the environment receives the shutdown signal.

Our current flow looks like this:
1. Initialize sdk clients and internal variables
2. get objects from s3
3. start process
4. do some work
5. terminate process

given that the work done in step 4 just needs to assume that the process is already running, this gives us that moving steps 3 and 5 to an extension would greatly simplify our code while retaining all retry and fallback logic intact.

you guys have plans to add a sample for java extensions?

**Comment by hariohmprasath** [comment]
Hi @RobertoC27,
Are you still looking for a sample extension on java? I can put together one for you, if you have not done it already

Thanks,
Hari

**Comment by RobertoC27** [comment]
Thanks for your input @hariohmprasath, I still have not managed to get the java extension running, and would greatly appreciate that!

Roberto

**Comment by hariohmprasath** [comment]
Hi @RobertoC27,
I was able to get a java 11 external extension working. Submitted a pull request and working with the team for review. Meanwhile you can look the changes in my repo and get started
[Github](https://github.com/hariohmprasath/aws-lambda-extensions/tree/main/java-example-extension)

Have fun :) 

Thanks,
Hari
