### ISSUE TITLE
Any example of Cross - Language External Extension

### ISSUE THREAD

**Issue by nirav1911** [aws-samples/aws-lambda-extensions#61]
I would like to see examples where the lambda extension is written in different language than the actual lambda function. Eg. Lambda extension written in Python and Lambda function in Java or vice versa. Is it possible? Are there any examples like that?

**Comment by DmitryGulin** [comment]
This repository has a couple of examples already, e.g.:
- [go-example-logs-api-extension](https://github.com/aws-samples/aws-lambda-extensions/tree/main/go-example-logs-api-extension) demonstrates building Go extension to capture NodeJS function logs;
- [csharp-example-extension](https://github.com/aws-samples/aws-lambda-extensions/tree/main/csharp-example-extension) has an option to create a self-contained extension, which can be used with any supported Lambda runtime. See [Building single binary file extensions for AWS Lambda with .NET](https://aws.amazon.com/blogs/compute/building-single-binary-file-extensions-for-aws-lambda-with-net/) for more details on building self-contained extensions with .NET.

In general, you should be able to use any programming language, that would create an executable for x64 or ARM64 Linux platform, to build a runtime independent extension.

**Comment by jledesma-opsguru** [comment]
Hi folks. @DmitryGulin  @nirav1911 I know this post is already closed, but I would like to know if there is possible to create an extension (in python) that could be invoked from inside of a lambda (in go) passing a payload and expecting a response. I was thinking in something similar to the SSM layer that could be invoked using an endpoint.

**Comment by DmitryGulin** [comment]
@jledesma-opsguru , yes, you should be able to create an extension that would listen to an endpoint, so that Lambda code can communicate with it.
Keep in mind, though, that .py and .pyc files will require Python runtime, which is not provided for a non-Python Lambda function. Thus, you'll have to either package runtime with your extension or find a way to compile Python scripts into an x64 or Arm64 Linux executable.
