### ISSUE TITLE
Makefile name incorrect for s3 logs extension

### ISSUE THREAD

**Issue by dianaalse** [aws-samples/aws-lambda-extensions#62]
For S3-Logs Extension Demo using .zip archive the makefile name should be corrected to Makefile instead of makefile, otherwise the commmand sam build will fail with error
Makefile not found at /../aws-lambda-extensions/s3-logs-extension-demo-zip-archive/extensionssrc/Makefile

**Comment by julianwood** [comment]
Thanks for spotting. I think this worked previously, A SAM update could have made this more explicit.
